import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import localFont from "next/font/local";

const pelak = localFont({
  src: [
    {
      path: '../public/fonts/PelakFA-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/PelakFA-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/PelakFA-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/PelakFA-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/PelakFA-Black.otf',
      weight: '900',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa'>
      <body className={pelak.className} >
        <NextUIProvider locale='fa-AF' >
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
