import type { Metadata } from "next";
import { NextUIProvider } from "@nextui-org/react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import AppWrappers from "../components/AppWrappers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir="rtl">
      <header>
        <Header />
      </header>

      <body className="">
        <NextUIProvider locale='fa-AF'>
          <AppWrappers>{children}</AppWrappers>
        </NextUIProvider>
      </body>
      
      <footer>
        <Footer />
      </footer>
    </html>
  );
}